- name:
  - lena_leonie
- channels:
  - conda-forge
  - defaults
- dependencies:
  - python=3.8
  - pip
  - pandas
  - argparse
  - torch
  - torch.nn
  - math
  - transformers
  - torch.optim
  - datasets
  - os
  - csv
